name 'vitadisplays-oxid'
version '0.0.1'

author 'Matthias Krause'
license ''
project_page ''
source ''
summary ''
description ''
dependency 'puppetlabs-stdlib', '4.1.0'
dependency 'puppetlabs-apt', '1.4.0'
dependency 'puppetlabs/apache', '0.10.0'
dependency 'puppetlabs/mysql', '2.1.0'
dependency 'maestrodev/wget', '1.3.1'
dependency 'nodes/php', '0.7.0'
dependency 'camptocamp/augeas', '0.0.1'

