name 'vitadisplays-oxid'
version '0.0.1-SNAPSHOT'

author 'Matthias Krause'
license ''
project_page ''
source ''
summary ''
description ''
dependency 'puppetlabs/stdlib', '>=4.1.0'
dependency 'puppetlabs/apt', '>=1.1.0'
